### ISSUE TITLE
AttributeError: module 'utilities.rqworker' has no attribute ''

### ISSUE THREAD

**Issue by havokoc** [netbox-community/netbox-docker#1689]
### Current Behavior

Trying to start the docker container version v4.6.1-5.0.1 via kubernetes with the command`python manage.py rqworker` crashes the container with an error message

This was working with no issues in v4.5.5-4.0.2

### Expected Behavior

RQWorker should start without spewing out an error message

### Docker Compose Version

Openshift

### Docker Version

```text
Openshift
```

### The git Revision

none as I'm using the docker.io container

### The git Status

```text
none as I'm using the docker.io container
```

### Startup Command

None as I'm using openshift/kubernetes

### NetBox Logs

```text
↩ Skip creating the superuser
✅ Initialisation is done.
🧬 loaded config '/etc/netbox/config/configuration.py'
🧬 loaded config '/etc/netbox/config/extra.py'
🧬 loaded config '/etc/netbox/config/logging.py'
🧬 loaded config '/etc/netbox/config/plugins.py'
🧬 loaded config '/etc/netbox/config/redis_sentinel.py'
Traceback (most recent call last):
  File "/opt/netbox/venv/lib/python3.14/site-packages/rq/utils.py", line 210, in import_attribute
    attribute_owner = getattr(module, attribute_owner_name)
AttributeError: module 'utilities.rqworker' has no attribute ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/netbox/netbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.14/site-packages/django/core/management/__init__.py", line 443, in execute_from_command_line
    utility.execute()
    ~~~~~~~~~~~~~~~^^
  File "/opt/netbox/venv/lib/python3.14/site-packages/django/core/management/__init__.py", line 437, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.14/site-packages/django/core/management/base.py", line 420, in run_from_argv
    self.execute(*args, **cmd_options)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.14/site-packages/django/core/management/base.py", line 464, in execute
    output = self.handle(*args, **options)
  File "/opt/netbox/netbox/core/management/commands/rqworker.py", line 38, in handle
    super().handle(*args, **options)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.14/site-packages/django_rq/management/commands/rqworker.py", line 100, in handle
    w = get_worker(*args, **worker_kwargs)
  File "/opt/netbox/venv/lib/python3.14/site-packages/django_rq/workers.py", line 56, in get_worker
    worker_class = get_worker_class(worker_class)
  File "/opt/netbox/venv/lib/python3.14/site-packages/django_rq/workers.py", line 38, in get_worker_class                                                                                                                                                           worker_class = import_attribute(worker_class)
  File "/opt/netbox/venv/lib/python3.14/site-packages/rq/utils.py", line 212, in import_attribute
    raise ValueError(f'Invalid attribute name: {attribute_name}')
ValueError: Invalid attribute name: NetBoxRQWorker
```

### Content of docker-compose.override.yml

```yaml
None as I'm using openshift/kubernetes
```

**Comment by havokoc** [comment]
I have also tried running it with `/opt/netbox/venv/bin/python /opt/netbox/netbox/manage.py rqworker high default low` with the same results as above
