### ISSUE TITLE
TypeError: send_webhook() got an unexpected keyword argument 'event_type'

### ISSUE THREAD

**Issue by alexandrud** [netbox-community/netbox-docker#1354]
### Current Behavior

After an upgrade from 4.0.6 to 4.1.7 I started seeing the following error:

```19:54:43 default: extras.webhooks.send_webhook(data={'id': 3, 'url': '/api/virtualization/virtual-machines/3/', 'display_url': ..., event_rule=<EventRule: linux-system-update>, event_type='object_updated', model_name='virtualmachine', request_id=UUID('516ca67f-1ff6-4b99-bfd7-b2a898b2e66d'), snapshots={'prechange': {'created': '2024-09-12T08:14:07.211Z', 'description': '[IW] ..., timestamp='2024-11-22T19:54:43.583260+00:00', username='admin') (c3c158b7-0017-449f-a979-90ce588cf39e)
/opt/netbox/venv/lib/python3.11/site-packages/rq/job.py:486: RuntimeWarning: Pickled model instance's Django version 5.0.9 does not match the current version 5.0.7.
  self._func_name, self._instance, self._args, self._kwargs = self.serializer.loads(self.data)
19:54:43 [Job c3c158b7-0017-449f-a979-90ce588cf39e]: exception raised while executing (extras.webhooks.send_webhook)
Traceback (most recent call last):
  File "/opt/netbox/venv/lib/python3.11/site-packages/rq/worker.py", line 1430, in perform_job
    rv = job.perform()
         ^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.11/site-packages/rq/job.py", line 1280, in perform
    self._result = self._execute()
                   ^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.11/site-packages/rq/job.py", line 1317, in _execute
    result = self.func(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: send_webhook() got an unexpected keyword argument 'event_type'```

### Expected Behavior

The system was upgraded from 4.0.6 to 4.1.7.

1. Create webhook
2. Create an event rule for virtual machine on event updated and set the webhook as action
3. Update a virtual machine object
4. Webhook is sent

This issue was also raised here: https://github.com/netbox-community/netbox/discussions/17819

### Docker Compose Version

Kubernetes 1.29

### Docker Version

```text
containerd v1.7.16
```

### The git Revision

netbox v4.1.7

### The git Status

```text
n/a
```

### Startup Command

docker compose up

### NetBox Logs

```text
:54:43 default: extras.webhooks.send_webhook(data={'id': 3, 'url': '/api/virtualization/virtual-machines/3/', 'display_url': ..., event_rule=<EventRule: linux-system-update>, event_type='object_updated', model_name='virtualmachine', request_id=UUID('516ca67f-1ff6-4b99-bfd7-b2a898b2e66d'), snapshots={'prechange': {'created': '2024-09-12T08:14:07.211Z', 'description': '[IW] ..., timestamp='2024-11-22T19:54:43.583260+00:00', username='admin') (c3c158b7-0017-449f-a979-90ce588cf39e)
/opt/netbox/venv/lib/python3.11/site-packages/rq/job.py:486: RuntimeWarning: Pickled model instance's Django version 5.0.9 does not match the current version 5.0.7.
  self._func_name, self._instance, self._args, self._kwargs = self.serializer.loads(self.data)
19:54:43 [Job c3c158b7-0017-449f-a979-90ce588cf39e]: exception raised while executing (extras.webhooks.send_webhook)
Traceback (most recent call last):
  File "/opt/netbox/venv/lib/python3.11/site-packages/rq/worker.py", line 1430, in perform_job
    rv = job.perform()
         ^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.11/site-packages/rq/job.py", line 1280, in perform
    self._result = self._execute()
                   ^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.11/site-packages/rq/job.py", line 1317, in _execute
    result = self.func(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: send_webhook() got an unexpected keyword argument 'event_type'
```

### Content of docker-compose.override.yml

```yaml
n/a
```

**Comment by alexandrud** [comment]
This was due to a mismatch between the netbox and worker images. netbox was running 4.1.7 and the worker was running 4.0.6.
