### ISSUE TITLE
LDAP broken after upgrade to 1.x

### ISSUE THREAD

**Issue by karrots** [netbox-community/netbox-docker#424]
## Current Behavior

Upgraded from 0.27 to 1.0.1 per the instructions. Everything starts up fine but LDAP authentication doesn't work. Logs don't show `/etc/netbox/config/ldap/ldap_config.py` getting loaded
...

## Expected Behavior

Loading of `/etc/netbox/config/ldap/ldap_config.py` and LDAP authentication working like with 0.27
...

## Debug Information

docker-compose version
```
docker-compose version 1.25.0, build unknown
docker-py version: 4.1.0
CPython version: 3.8.5
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020
```

docker version
```
Client:
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.13.8
 Git commit:        afacb8b7f0
 Built:             Fri Dec 18 12:15:19 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.8
  Git commit:       afacb8b7f0
  Built:            Fri Dec  4 23:02:49 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu2.2
  GitCommit:
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:
 docker-init:
  Version:          0.18.0
  GitCommit:
```

git rev-parse HEAD
`4dd7a51c7d79b097dea8ee7cf493dff00ebf50c3`

Command used to start
`docker-compose up -d`

The output of `docker inspect netboxcommunity/netbox:latest --format "{{json .Config.Labels}}"`:
`
```json
{
   "BUILD_REASON":"netbox-docker",
   "NETBOX_GIT_BRANCH":"HEAD",
   "NETBOX_GIT_REF":"856d2e317605011e16a17bd87062721737ce3474",
   "NETBOX_GIT_URL":"https://github.com/netbox-community/netbox.git",
   "ORIGINAL_TAG":"docker.io/netboxcommunity/netbox:v2.10.4",
   "org.label-schema.build-date":"2021-02-03T14:30+00:00",
   "org.label-schema.description":"A container based distribution of Netbox, the free and open IPAM and DCIM solution.",
   "org.label-schema.name":"Netbox Docker",
   "org.label-schema.schema-version":"1.0",
   "org.label-schema.url":"https://github.com/netbox-community/netbox-docker",
   "org.label-schema.usage":"https://github.com/netbox-community/netbox-docker/wiki",
   "org.label-schema.vcs-ref":"4dd7a51c7d79b097dea8ee7cf493dff00ebf50c3",
   "org.label-schema.vcs-url":"https://github.com/netbox-community/netbox-docker.git",
   "org.label-schema.vendor":"The netbox-docker contributors.",
   "org.label-schema.version":"1.0.1",
   "org.opencontainers.image.authors":"The netbox-docker contributors.",
   "org.opencontainers.image.created":"2021-02-03T14:30+00:00",
   "org.opencontainers.image.description":"A container based distribution of Netbox, the free and open IPAM and DCIM solution.",
   "org.opencontainers.image.documentation":"https://github.com/netbox-community/netbox-docker/wiki",
   "org.opencontainers.image.licenses":"Apache-2.0",
   "org.opencontainers.image.revision":"4dd7a51c7d79b097dea8ee7cf493dff00ebf50c3",
   "org.opencontainers.image.source":"https://github.com/netbox-community/netbox-docker.git",
   "org.opencontainers.image.title":"Netbox Docker",
   "org.opencontainers.image.url":"https://github.com/netbox-community/netbox-docker",
   "org.opencontainers.image.vendor":"The netbox-docker contributors.",
   "org.opencontainers.image.version":"1.0.1"
}
```

The output of `docker-compose logs netbox`:
https://gist.github.com/karrots/f1312d393fdbc6ed7447028b3ea86133

**Comment by tobiasge** [comment]
In Netbox version 2.9 and above LDAP settings are loaded when the `netbox.authentication.LDAPBackend` is instantiated. This only happens when you set those to variables in the configuration:
```python
REMOTE_AUTH_ENABLED = True
REMOTE_AUTH_BACKEND = 'netbox.authentication.LDAPBackend'
```

Could you check if the settings are loaded when you load that class manually. Please execute these commands inside the netbox container (`docker-compose exec netbox /bin/bash`):
```bash
source /opt/netbox/venv/bin/activate
./manage.py shell
```
and the run this in the python shell:
```python
from pprint import pprint
from netbox.authentication import LDAPBackend

lb = LDAPBackend()
pprint(lb.settings.__dict__)
```

Are the correct settings displayed?

**Comment by karrots** [comment]
This setup was working fine with LDAP on 0.27 and Netbox 2.10.3 prior to migration to 1.x. I have the REMOTE_AUTH_* options in the `docker-compose.override.yml`

The docker container seems to only have python 3.8 on it so pprint doesn't work. Nor does it want to import `LDAPBackend`

```
from netbox.authentication import LDAPBackend

lb = LDAPBackend()
print(lb.settings.__dict__)
  File "<console>", line 2
    from netbox.authentication import LDAPBackend
                                                ^
SyntaxError: multiple statements found while compiling a single statement
```

**Comment by tobiasge** [comment]
I checked all the commands In posted in one of my test environments. They should run. The error message your container shows, indicates a problem with copy and paste of the commands. `pprint` has been in Python for long time (I think 1997), so using only version 3.8 should not be a problem.

**Comment by karrots** [comment]
ok I typed it in manually and got this.

```
>>> from pprint import pprint
>>> from netbox.authentication import LDAPBackend
>>> lb = LDAPBackend()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/opt/netbox/netbox/netbox/authentication.py", line 150, in __new__
    from netbox import ldap_config
ImportError: cannot import name 'ldap_config' from 'netbox' (/opt/netbox/netbox/netbox/__init__.py)
```

**Comment by tobiasge** [comment]
Could you check if the `ldap_config.py` is present in the container? It should be in `/opt/netbox/netbox/netbox/`.
What is in your `docer-compose.override.yml`?

**Comment by karrots** [comment]
```
(venv) bash-5.1$ ls /opt/netbox/netbox/netbox/
__init__.py               api                       configuration.py          context_processors.py     releases.py               urls.py
__pycache__               authentication.py         configuration.testing.py  forms.py                  settings.py               views
admin.py                  configuration.example.py  constants.py              middleware.py             tests                     wsgi.py
```
`docker-compuse.override.yml`
https://gist.github.com/karrots/142aea73d06afd0f6dd8d62874ab8b35

**Comment by tobiasge** [comment]
You have two services named `netbox` in your `docker-compose.override.yml`. When you remove line 29 from it, the correct image will be used.

**Comment by karrots** [comment]
When I do that it doesn't start on 8080 anymore and I can't access the service.

**Comment by karrots** [comment]
I take that back this time it worked fine and LDAP works. I wonder if the 2.10.4 build is different from the 2.10.3 build I was using yesterday.

**Comment by holmesb** [comment]
Same error when trying to start netbox in kubernetes:
![image](https://user-images.githubusercontent.com/5072156/124615467-36601480-de6d-11eb-8a53-76b02638de1a.png)

That gist is a broken link so can't see what the "line 29" fix is.  Any chance you can explain?  

Interestingly, the file mentioned in the error: `/opt/netbox/netbox/netbox/__init__.py` is empy (0 kb).  Could this be related?  
Using docker image: netboxcommunity/netbox:v2.10.4

**Comment by tobiasge** [comment]
> Using docker image: netboxcommunity/netbox:v2.10.4

You should be using the -ldap image.

**Comment by holmesb** [comment]
Thanks @tobiasge, yes upgrading to netboxcommunity/netbox:v2.11.7-ldap got past this error and allowed the pod to start.  My ldap credentials are not working when trying to login to the webui though.  "_Please enter a correct username and password_".  Is there some log file that can help diagnose ldap issues?  Nothing relevent in the pod\stdout logs.

**Comment by holmesb** [comment]
In netbox.yaml, I've set: 
LOGGING: {"disable_existing_loggers":"False,","handlers":{"console":{"class":"logging.StreamHandler"}},"loggers":{"django_auth_ldap":{"handlers\"":"console","level":"DEBUG"}},"version":1}

But nothing new in stdout\pod logs.

**Comment by holmesb** [comment]
My user account wasn't in AUTH_LDAP_REQUIRE_GROUP.   Now logged in :-)

**Comment by FaserF** [comment]
Got the same issue, I am using the latest ldap image. 

/opt/netbox/netbox/netbox/ does not contain a ldap_config file. 
in /etc/netbox/config/ldap_config.py does exist.

Any hints?
